### ISSUE TITLE
Permission to limit chest shop creation

### ISSUE THREAD

**Issue by sluhtie** [Senne98/Chest-Winkel#2]
Hey, I'd like to ask if you could add a permission to limit the amount of chest shops a user can create?
Something like:
- chestshop.limit.<integer>
- chestshop.limit.unlimited

**Comment by Senne98** [comment]
That's a great idea, might add that in the next update.

**Comment by sluhtie** [comment]
Also is it able to add more chest shop blocks? For example, a normal chest as well? Maybe add like a config options with allowed blocks

**Comment by Senne98** [comment]
I don't know, I don't like the look of chests :). But maybe as a config that defaults to false.
